spring:
    jpa:
        hibernate:
            ddl-auto: update

    datasource:
        url: jdbc:mysql://localhost:3306/mydb?useSSL=false
        username: admin
        password: admin
server:
    port: 8080